# Generated by Django 4.0 on 2023-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UzAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('rangi', models.CharField(max_length=255)),
                ('narxi', models.CharField(max_length=255)),
            ],
        ),
    ]
